# .github/workflows/add-livecontainer.yml

name: Add LiveContainer App from src

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run daily at 3am UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apps.json with LiveContainer
        run: |
          # download remote json
          curl -sL "https://raw.githubusercontent.com/LiveContainer/LiveContainer/refs/heads/main/apps.json" -o remote.json

          # extract the livecontainer app object
          live_app=$(jq '.apps[] | select(.name == "LiveContainer")' remote.json)

          # exit if app is not found in remote source
          if [ -z "$live_app" ] || [ "$live_app" == "null" ]; then
            echo "LiveContainer app not found in remote source. No action taken."
            exit 0
          fi

          # extract bundle id for the check
          bundle_id=$(echo "$live_app" | jq -r '.bundleIdentifier')

          # exit if app with the same bundle id already exists
          if jq -e --arg bid "$bundle_id" '.apps[] | select(.bundleIdentifier == $bid)' apps.json > /dev/null; then
            echo "LiveContainer app with bundle ID ($bundle_id) already exists. No action taken."
            exit 0
          fi

          # add the new app object to the local apps.json
          echo "Adding LiveContainer app to apps.json"
          jq --argjson new_app "$live_app" '.apps += [$new_app]' apps.json > tmp.$$.json && mv tmp.$$.json apps.json

      - name: Commit and push if changes exist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Add LiveContainer app to repo"
          file_pattern: apps.json
